/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include <Wire.h>
#include <LiquidCrystalIO.h>
#include <IoAbstractionWire.h>
#include <JoystickSwitchInput.h>
#include <RuntimeMenuItem.h>
#include <IoAbstraction.h>
#include <EepromItemStorage.h>
#include "tcMenuLiquidCrystal.h"

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern LiquidCrystal lcd;
extern LiquidCrystalRenderer renderer;

// Any externals needed by IO expanders, EEPROMs etc


// Global Menu Item exports
extern EnumMenuItem menuDigOut;
extern TextMenuItem menuAnIn;
extern TextMenuItem menuDigIn;
extern BackMenuItem menuBackTesztelo;
extern SubMenuItem menuTesztelo;
extern EnumMenuItem menuJatek;
extern ActionMenuItem menuNewActionItem;
extern ListRuntimeMenuItem menuNewRuntimeList;
extern BooleanMenuItem menuGomb1;
extern BackMenuItem menuBackJatekValaszto;
extern SubMenuItem menuJatekValaszto;

// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return menuJatekValaszto; }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION AnIn(int id);
void CALLBACK_FUNCTION DigIn(int id);
void CALLBACK_FUNCTION DigOut(int id);
void CALLBACK_FUNCTION Gomb1(int id);
void CALLBACK_FUNCTION Jatek(int id);
void CALLBACK_FUNCTION Tesztelo(int id);
int fnNewRuntimeListRtCall(RuntimeMenuItem* item, uint8_t row, RenderFnMode mode, char* buffer, int bufferSize);

#endif // MENU_GENERATED_CODE_H
