/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

// Generated for Arduino AVR/Uno/Mega by TcMenu 4.4.0 on 2025-11-15T13:23:33.910904600Z.

#include <tcMenu.h>
#include "Gyerek_jatek_arduinomega_menu.h"

// Global variable declarations
const PROGMEM  ConnectorLocalInfo applicationInfo = { "Okos Jatek", "f7271d5a-6f58-4dfa-b268-54885035137a" };

LiquidCrystal lcd(0, 1, 2, 4, 5, 6, 7);
LiquidCrystalRenderer renderer(lcd, 16, 2);

// Global Menu Item declarations
const char enumStrDigOut_0[] PROGMEM = "test1";
const char enumStrDigOut_1[] PROGMEM = "test2";
const char* const enumStrDigOut[] PROGMEM  = { enumStrDigOut_0, enumStrDigOut_1 };
const PROGMEM EnumMenuInfo minfoDigOut = { "DigOut", 11, 0xffff, 1, DigOut, enumStrDigOut };
EnumMenuItem menuDigOut(&minfoDigOut, 0, nullptr, INFO_LOCATION_PGM);
const PROGMEM AnyMenuInfo minfoAnIn = { "AnIn", 9, 0xffff, 0, AnIn };
TextMenuItem menuAnIn(&minfoAnIn, "", 10, &menuDigOut, INFO_LOCATION_PGM);
const PROGMEM AnyMenuInfo minfoDigIn = { "DigIn", 8, 0xffff, 0, DigIn };
TextMenuItem menuDigIn(&minfoDigIn, "", 20, &menuAnIn, INFO_LOCATION_PGM);
const PROGMEM SubMenuInfo minfoTesztelo = { "Teszt (fel-le)", 7, 0xffff, 0, Tesztelo };
BackMenuItem menuBackTesztelo(&minfoTesztelo, &menuDigIn, INFO_LOCATION_PGM);
SubMenuItem menuTesztelo(&minfoTesztelo, &menuBackTesztelo, nullptr, INFO_LOCATION_PGM);
const char enumStrJatek_0[] PROGMEM = "Cyclon";
const char enumStrJatek_1[] PROGMEM = "Item2";
const char* const enumStrJatek[] PROGMEM  = { enumStrJatek_0, enumStrJatek_1 };
const PROGMEM EnumMenuInfo minfoJatek = { "Jatek", 10, 0xffff, 1, Jatek, enumStrJatek };
EnumMenuItem menuJatek(&minfoJatek, 0, &menuTesztelo, INFO_LOCATION_PGM);
const PROGMEM AnyMenuInfo minfoNewActionItem = { "New ActionItem", 5, 0xffff, 0, NO_CALLBACK };
ActionMenuItem menuNewActionItem(&minfoNewActionItem, &menuJatek, INFO_LOCATION_PGM);
const PROGMEM AnyMenuInfo minfoNewRuntimeList = { "New Runtime List", 4, 0xffff, 0, NO_CALLBACK };
ListRuntimeMenuItem menuNewRuntimeList(&minfoNewRuntimeList, 10, fnNewRuntimeListRtCall, &menuNewActionItem, INFO_LOCATION_PGM);
const PROGMEM BooleanMenuInfo minfoGomb1 = { "gomb1", 3, 0xffff, 1, Gomb1, NAMING_TRUE_FALSE };
BooleanMenuItem menuGomb1(&minfoGomb1, false, &menuNewRuntimeList, INFO_LOCATION_PGM);
const PROGMEM SubMenuInfo minfoJatekValaszto = { "JatekValaszto", 1, 0xffff, 0, NO_CALLBACK };
BackMenuItem menuBackJatekValaszto(&minfoJatekValaszto, nullptr, INFO_LOCATION_PGM);
SubMenuItem menuJatekValaszto(&minfoJatekValaszto, &menuBackJatekValaszto, &menuGomb1, INFO_LOCATION_PGM);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    setSizeBasedEEPROMStorageEnabled(false);
    // Code generated by plugins and new operators.
    Wire.begin();
    lcd.setIoAbstraction(ioFrom8574(0x27, 0xff, &Wire));
    lcd.begin(16, 2);
    renderer.setUpdatesPerSecond(2);
    lcd.configureBacklightPin(3);
    lcd.backlight();
    switches.init(internalDigitalIo(), SWITCHES_POLL_EVERYTHING, true);
    switches.addSwitch(53, NULL);
    switches.onRelease(53, [](pinid_t /*key*/, bool held) {
            menuMgr.onMenuSelect(held);
        });
    setupAnalogJoystickEncoder(internalAnalogIo(), A9, [](int val) {
            menuMgr.valueChanged(val);
        });
    reinterpret_cast<JoystickSwitchInput*>(switches.getEncoder())->setTolerance(0.5, 0.1);
    menuMgr.initWithoutInput(&renderer, &menuJatekValaszto);
}

